#!/bin/sh

set -eu

ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"

PYTHON="${PYTHON:-python3}"

echo "Generating module manifest..."

#git stash

"$PYTHON" scripts/manifest.py \
    clang++ \
    -Iinclude \
    -std=c++20 \
    -DRAWR_MODULE \
    --root . \
    --manifest module.manifest \
    --modules-- \
    include/rawr.hpp \
    include/rawr

git add module.manifest

# echo "Generating amalgam..."

# rm -f include/rawr.amalgam.hpp
# git add include/rawr.amalgam.hpp

# if "$PYTHON" scripts/amalgam.py \
#     -I include \
#     include/rawr.hpp \
#     include/rawr.amalgam.hpp
# then
#     git add include/rawr.amalgam.hpp
# else
#     echo "warning: amalgamation failed; committing with amalgam deleted" >&2
#     git add include/rawr.amalgam.hpp
# fi

#git stash pop
