services:
  gcc:
    build:
      context: .
      dockerfile: gcc.dockerfile
    volumes:
      - ../..:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true

  clang:
    build:
      context: .
      dockerfile: clang.dockerfile
    volumes:
      - ../..:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
