// GENERATED — do not edit
#if RAWR_ARCH_X86
    #undef RAWR_ABI_SYSV_TRAMPOLINE
#elif RAWR_ARCH_X64
    #undef RAWR_ABI_SYSV_TRAMPOLINE
#elif RAWR_ARCH_ARM32
    #undef RAWR_ABI_SYSV_TRAMPOLINE
#elif RAWR_ARCH_ARM64
    #undef RAWR_ABI_SYSV_TRAMPOLINE
#elif RAWR_ARCH_RISCV32
    #undef RAWR_ABI_SYSV_TRAMPOLINE
#elif RAWR_ARCH_RISCV64
    #undef RAWR_ABI_SYSV_TRAMPOLINE
#else
    #undef RAWR_ABI_SYSV_HAS_TRAMPOLINE
    #undef RAWR_ABI_SYSV_TRAMPOLINE
#endif
#undef RAWR_ABI_SYSV_HAS_TRAMPOLINE
#undef RAWR_ABI_SYSV_TRAMPOLINE_RISCV64
#undef RAWR_ABI_SYSV_TRAMPOLINE_RISCV32
#undef RAWR_ABI_SYSV_TRAMPOLINE_ARM64
#undef RAWR_ABI_SYSV_TRAMPOLINE_ARM32
#undef RAWR_ABI_SYSV_TRAMPOLINE_X64
#undef RAWR_ABI_SYSV_TRAMPOLINE_X86
#include "rawr/detection/arch.undef.pp"
#if RAWRSCAN_METADATA
    #undef RAWR_PP_MODULE
#endif
