//// rawr/lib/pp.hpp – Preprocessor utility macros (FOR_EACH, NARG, CAT, …).
//
// This header provides reusable low‑level preprocessor iteration and counting
// macros that are shared by rawr::restruct, rawr::fmt, rawr::serialize, and
// others. Up to 256 arguments are supported; the limit can be raised by adding
// more RAWR_PP_FOR_EACH_n macros.
#pragma region rawr/lib/pp.hpp

#ifndef RAWR_UNITY
    #pragma once
#endif

#define RAWR_PP_WHEN_0(...)
#define RAWR_PP_WHEN_1(...)  __VA_ARGS__
#define RAWR_PP_WHEN(C, ...) RAWR_PP_CAT_CALL(RAWR_PP_WHEN_, C, __VA_ARGS__)

#define RAWR_PP_IF_0(_, F)  F
#define RAWR_PP_IF_1(T, _)  T
#define RAWR_PP_IF(C, T, F) RAWR_PP_CAT_CALL(RAWR_PP_IF_, C, T, F)


// ── expansion forcing ─────────────────────────────────────────────────────────
#define RAWR_PP_EXPAND(...)  __VA_ARGS__
#define RAWR_PP_EXPAND2(...) RAWR_PP_EXPAND(RAWR_PP_EXPAND(__VA_ARGS__))
#define RAWR_PP_EXPAND3(...) RAWR_PP_EXPAND2(RAWR_PP_EXPAND2(__VA_ARGS__))

// ── core ──────────────────────────────────────────────────────────────────────
#define RAWR_PP_EMPTY_SEP()
#define RAWR_PP_COMMA_SEP() ,
#define RAWR_PP_STRIP(plist) RAWR_PP_EXPAND plist
#define RAWR_PP_PREPEND_PLIST(plist, ...) (__VA_ARGS__, RAWR_PP_STRIP(plist))

// ── element count ─────────────────────────────────────────────────────────────
#define RAWR_PP_CNT_(_1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,_17,_18,_19,_20,_21,_22,_23,_24,_25,_26,_27,_28,_29,_30,_31,_32,_33,_34,_35,_36,_37,_38,_39,_40,_41,_42,_43,_44,_45,_46,_47,_48,_49,_50,_51,_52,_53,_54,_55,_56,_57,_58,_59,_60,_61,_62,_63,_64,_65,_66,_67,_68,_69,_70,_71,_72,_73,_74,_75,_76,_77,_78,_79,_80,_81,_82,_83,_84,_85,_86,_87,_88,_89,_90,_91,_92,_93,_94,_95,_96,_97,_98,_99,_100,_101,_102,_103,_104,_105,_106,_107,_108,_109,_110,_111,_112,_113,_114,_115,_116,_117,_118,_119,_120,_121,_122,_123,_124,_125,_126,_127,_128,_129,_130,_131,_132,_133,_134,_135,_136,_137,_138,_139,_140,_141,_142,_143,_144,_145,_146,_147,_148,_149,_150,_151,_152,_153,_154,_155,_156,_157,_158,_159,_160,_161,_162,_163,_164,_165,_166,_167,_168,_169,_170,_171,_172,_173,_174,_175,_176,_177,_178,_179,_180,_181,_182,_183,_184,_185,_186,_187,_188,_189,_190,_191,_192,_193,_194,_195,_196,_197,_198,_199,_200,_201,_202,_203,_204,_205,_206,_207,_208,_209,_210,_211,_212,_213,_214,_215,_216,_217,_218,_219,_220,_221,_222,_223,_224,_225,_226,_227,_228,_229,_230,_231,_232,_233,_234,_235,_236,_237,_238,_239,_240,_241,_242,_243,_244,_245,_246,_247,_248,_249,_250,_251,_252,_253,_254,_255,_256,\
    N,...) N
#define RAWR_PP_CNT(...) RAWR_PP_EXPAND(RAWR_PP_CNT_(__VA_ARGS__,\
    256,255,254,253,252,251,250,249,248,247,246,245,244,243,242,241,240,239,238,237,236,235,234,233,232,231,230,229,228,227,226,225,224,223,222,221,220,219,218,217,216,215,214,213,212,211,210,209,208,207,206,205,204,203,202,201,200,199,198,197,196,195,194,193,192,191,190,189,188,187,186,185,184,183,182,181,180,179,178,177,176,175,174,173,172,171,170,169,168,167,166,165,164,163,162,161,160,159,158,157,156,155,154,153,152,151,150,149,148,147,146,145,144,143,142,141,140,139,138,137,136,135,134,133,132,131,130,129,128,127,126,125,124,123,122,121,120,119,118,117,116,115,114,113,112,111,110,109,108,107,106,105,104,103,102,101,100,99,98,97,96,95,94,93,92,91,90,89,88,87,86,85,84,83,82,81,80,79,78,77,76,75,74,73,72,71,70,69,68,67,66,65,64,63,62,61,60,59,58,57,56,55,54,53,52,51,50,49,48,47,46,45,44,43,42,41,40,39,38,37,36,35,34,33,32,31,30,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1\
))

// ── concatenate + call ────────────────────────────────────────────────────────
#define RAWR_PP_CAT_CALL_(M, N, ...) M##N(__VA_ARGS__)
#define RAWR_PP_CAT_CALL(M, N, ...)  RAWR_PP_EXPAND(RAWR_PP_CAT_CALL_(M, N, __VA_ARGS__))

// ── arity dispatch on a parenthesized argument list ───────────────────────────
// RAWR_PP_DISPATCH_PLIST_BY_ARITY(FOO_, (a, b))  →  FOO_2(a, b)
#define RAWR_PP_DISPATCH_PLIST_BY_ARITY(M, plist) \
    RAWR_PP_CAT_CALL(M, RAWR_PP_CNT(RAWR_PP_STRIP(plist)), RAWR_PP_STRIP(plist))

// ── iteration with separator (canonical) ─────────────────────────────────────
// Elements are parenthesized: (a)(b)(c)
// Sep is a token or RAWR_PP_COMMA or RAWR_PP_EMPTY
#pragma region RAWR_PP_FOR
#define RAWR_PP_FOR_1(M,Sep,Ctx,Head,...)   M(Ctx,Head)
#define RAWR_PP_FOR_2(M,Sep,Ctx,Head,...)   M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_1(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_3(M,Sep,Ctx,Head,...)   M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_2(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_4(M,Sep,Ctx,Head,...)   M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_3(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_5(M,Sep,Ctx,Head,...)   M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_4(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_6(M,Sep,Ctx,Head,...)   M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_5(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_7(M,Sep,Ctx,Head,...)   M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_6(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_8(M,Sep,Ctx,Head,...)   M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_7(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_9(M,Sep,Ctx,Head,...)   M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_8(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_10(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_9(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_11(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_10(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_12(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_11(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_13(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_12(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_14(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_13(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_15(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_14(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_16(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_15(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_17(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_16(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_18(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_17(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_19(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_18(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_20(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_19(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_21(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_20(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_22(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_21(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_23(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_22(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_24(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_23(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_25(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_24(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_26(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_25(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_27(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_26(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_28(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_27(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_29(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_28(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_30(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_29(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_31(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_30(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_32(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_31(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_33(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_32(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_34(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_33(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_35(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_34(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_36(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_35(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_37(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_36(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_38(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_37(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_39(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_38(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_40(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_39(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_41(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_40(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_42(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_41(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_43(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_42(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_44(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_43(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_45(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_44(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_46(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_45(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_47(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_46(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_48(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_47(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_49(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_48(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_50(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_49(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_51(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_50(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_52(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_51(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_53(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_52(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_54(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_53(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_55(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_54(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_56(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_55(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_57(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_56(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_58(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_57(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_59(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_58(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_60(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_59(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_61(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_60(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_62(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_61(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_63(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_62(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_64(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_63(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_65(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_64(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_66(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_65(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_67(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_66(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_68(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_67(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_69(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_68(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_70(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_69(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_71(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_70(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_72(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_71(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_73(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_72(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_74(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_73(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_75(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_74(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_76(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_75(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_77(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_76(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_78(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_77(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_79(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_78(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_80(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_79(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_81(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_80(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_82(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_81(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_83(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_82(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_84(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_83(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_85(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_84(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_86(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_85(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_87(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_86(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_88(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_87(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_89(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_88(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_90(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_89(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_91(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_90(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_92(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_91(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_93(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_92(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_94(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_93(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_95(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_94(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_96(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_95(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_97(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_96(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_98(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_97(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_99(M,Sep,Ctx,Head,...)  M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_98(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_100(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_99(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_101(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_100(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_102(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_101(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_103(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_102(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_104(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_103(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_105(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_104(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_106(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_105(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_107(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_106(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_108(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_107(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_109(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_108(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_110(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_109(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_111(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_110(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_112(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_111(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_113(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_112(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_114(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_113(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_115(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_114(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_116(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_115(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_117(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_116(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_118(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_117(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_119(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_118(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_120(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_119(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_121(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_120(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_122(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_121(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_123(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_122(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_124(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_123(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_125(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_124(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_126(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_125(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_127(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_126(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_128(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_127(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_129(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_128(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_130(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_129(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_131(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_130(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_132(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_131(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_133(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_132(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_134(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_133(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_135(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_134(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_136(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_135(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_137(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_136(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_138(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_137(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_139(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_138(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_140(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_139(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_141(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_140(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_142(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_141(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_143(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_142(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_144(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_143(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_145(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_144(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_146(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_145(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_147(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_146(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_148(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_147(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_149(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_148(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_150(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_149(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_151(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_150(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_152(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_151(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_153(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_152(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_154(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_153(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_155(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_154(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_156(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_155(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_157(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_156(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_158(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_157(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_159(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_158(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_160(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_159(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_161(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_160(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_162(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_161(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_163(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_162(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_164(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_163(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_165(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_164(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_166(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_165(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_167(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_166(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_168(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_167(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_169(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_168(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_170(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_169(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_171(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_170(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_172(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_171(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_173(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_172(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_174(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_173(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_175(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_174(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_176(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_175(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_177(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_176(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_178(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_177(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_179(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_178(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_180(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_179(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_181(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_180(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_182(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_181(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_183(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_182(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_184(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_183(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_185(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_184(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_186(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_185(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_187(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_186(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_188(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_187(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_189(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_188(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_190(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_189(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_191(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_190(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_192(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_191(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_193(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_192(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_194(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_193(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_195(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_194(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_196(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_195(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_197(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_196(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_198(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_197(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_199(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_198(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_200(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_199(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_201(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_200(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_202(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_201(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_203(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_202(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_204(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_203(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_205(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_204(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_206(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_205(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_207(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_206(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_208(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_207(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_209(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_208(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_210(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_209(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_211(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_210(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_212(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_211(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_213(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_212(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_214(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_213(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_215(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_214(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_216(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_215(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_217(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_216(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_218(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_217(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_219(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_218(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_220(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_219(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_221(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_220(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_222(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_221(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_223(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_222(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_224(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_223(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_225(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_224(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_226(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_225(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_227(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_226(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_228(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_227(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_229(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_228(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_230(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_229(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_231(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_230(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_232(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_231(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_233(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_232(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_234(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_233(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_235(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_234(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_236(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_235(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_237(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_236(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_238(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_237(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_239(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_238(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_240(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_239(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_241(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_240(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_242(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_241(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_243(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_242(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_244(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_243(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_245(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_244(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_246(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_245(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_247(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_246(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_248(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_247(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_249(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_248(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_250(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_249(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_251(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_250(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_252(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_251(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_253(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_252(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_254(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_253(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_255(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_254(M,Sep,Ctx,__VA_ARGS__))
#define RAWR_PP_FOR_256(M,Sep,Ctx,Head,...) M(Ctx,Head) Sep() RAWR_PP_EXPAND(RAWR_PP_FOR_255(M,Sep,Ctx,__VA_ARGS__))
#pragma endregion RAWR_PP_FOR

// ── dispatch ──────────────────────────────────────────────────────────────────
#define RAWR_PP_DISP_SEP_(N,M,Sep,Ctx,...) RAWR_PP_FOR_##N(M,Sep,Ctx,__VA_ARGS__)
#define RAWR_PP_DISP_SEP(N,M,Sep,Ctx,...)  RAWR_PP_EXPAND(RAWR_PP_DISP_SEP_(N,M,Sep,Ctx,__VA_ARGS__))

// ── FOR is FOR_SEP with empty separator ───────────────────────────────────────
#define RAWR_PP_EACH_SEP_CTX(M, Sep, Ctx, ...) RAWR_PP_EXPAND3(RAWR_PP_DISP_SEP(RAWR_PP_CNT(__VA_ARGS__), M, Sep, Ctx, __VA_ARGS__))
#define RAWR_PP_EACH_CTX(M, Ctx, ...)          RAWR_PP_EACH_SEP_CTX(M, RAWR_PP_EMPTY_SEP, Ctx, __VA_ARGS__)

#define RAWR_PP_EACH_HELPER_(M, Head) M(Head)
#define RAWR_PP_EACH(M, ...)          RAWR_PP_EACH_SEP_CTX(RAWR_PP_EACH_HELPER_, RAWR_PP_EMPTY_SEP, M, __VA_ARGS__)
#define RAWR_PP_EACH_SEP(M, Sep, ...) RAWR_PP_EACH_SEP_CTX(RAWR_PP_EACH_HELPER_, Sep, M, __VA_ARGS__)

#define RAWR_PP_ENSURE_PAREN_CAT(a, b) RAWR_PP_ENSURE_PAREN_CAT_I(a, b)
#define RAWR_PP_ENSURE_PAREN_CAT_I(a, b) a ## b
#define RAWR_PP_ENSURE_PAREN_SECOND(_1, _2, ...) _2
#define RAWR_PP_IS_PAREN_PROBE(...) ~, 1
#define RAWR_PP_IS_PAREN_CHECK(...) RAWR_PP_ENSURE_PAREN_SECOND(__VA_ARGS__)
#define RAWR_PP_IS_PAREN(...) RAWR_PP_IS_PAREN_CHECK(RAWR_PP_IS_PAREN_PROBE __VA_ARGS__, 0)
#define RAWR_PP_ENSURE_PAREN_0(...) (__VA_ARGS__)
#define RAWR_PP_ENSURE_PAREN_1(...) __VA_ARGS__
#define RAWR_PP_ENSURE_PAREN_DISPATCH(cond, ...) RAWR_PP_ENSURE_PAREN_CAT(RAWR_PP_ENSURE_PAREN_, cond)(__VA_ARGS__)
#define RAWR_PP_ENSURE_PAREN(...) RAWR_PP_ENSURE_PAREN_DISPATCH(RAWR_PP_IS_PAREN(__VA_ARGS__), __VA_ARGS__)

#define RAWR_PP_CAT_(M, N, ...) M##N
#define RAWR_PP_CAT(M, N, ...)  RAWR_PP_CAT_(M, N)

#pragma endregion rawr/lib/pp.hpp
