// GENERATED — do not edit
#if RAWR_COMPILER_CLANG || RAWR_COMPILER_GCC
    #undef RAWR_COMPILER_FAMILY_GNU
#endif
#undef RAWR_COMPILER_FAMILY_GNU
#if defined(__clang__)
    #undef RAWR_COMPILER_VERSION_BUILD
    #undef RAWR_COMPILER_VERSION_PATCH
    #undef RAWR_COMPILER_VERSION_MINOR
    #undef RAWR_COMPILER_VERSION_MAJOR
    #undef RAWR_COMPILER_VERSION
    #undef RAWR_COMPILER_CLANG
#elif defined(__GNUC__) || defined(__GNUG__)
    #undef RAWR_COMPILER_VERSION_BUILD
    #undef RAWR_COMPILER_VERSION_PATCH
    #undef RAWR_COMPILER_VERSION_MINOR
    #undef RAWR_COMPILER_VERSION_MAJOR
    #undef RAWR_COMPILER_VERSION
    #undef RAWR_COMPILER_GCC
#elif defined(_MSC_VER)
    #undef RAWR_COMPILER_VERSION_BUILD
    #undef RAWR_COMPILER_VERSION_PATCH
    #undef RAWR_COMPILER_VERSION_MINOR
    #undef RAWR_COMPILER_VERSION_MAJOR
    #undef RAWR_COMPILER_VERSION
    #undef RAWR_COMPILER_MSVC
#else
    #undef RAWR_COMPILER_VERSION_BUILD
    #undef RAWR_COMPILER_VERSION_PATCH
    #undef RAWR_COMPILER_VERSION_MINOR
    #undef RAWR_COMPILER_VERSION_MAJOR
    #undef RAWR_COMPILER_VERSION
    #undef RAWR_COMPILER_UNKNOWN
#endif
#undef RAWR_COMPILER_UNKNOWN
#undef RAWR_COMPILER_MSVC
#undef RAWR_COMPILER_GCC
#undef RAWR_COMPILER_CLANG
#undef RAWR_DETECTION_MIN_MSVC_VERSION
#undef RAWR_DETECTION_MIN_CLANG_VERSION
#undef RAWR_DETECTION_MIN_GCC_VERSION
#if RAWRSCAN_METADATA
    #undef RAWR_PP_MODULE
#endif
